/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Streaming Symphonia decoder.
 *
 * Lifecycle
 * 1. `push(chunk)` feeds compressed data.
 * 2. `initialize(hint?)` probes once enough header/metadata is available.
 * 3. `decode()` returns PCM when a full packet is available, or `null` when
 *    more compressed input is needed.
 * 4. `closeInput()` signals end-of-input so the final packet/tail can flush.
 * 5. `free()` releases resources.
 */
export declare class SymphoniaDecoder {
  constructor()
  push(chunk: Buffer): void
  closeInput(): void
  /** Returns the number of compressed bytes currently available to the reader. */
  get bufferedBytes(): number
  get isProbed(): boolean
  /**
   * Probe the format and set up the decoder when enough input is available.
   * `codec_registry_hint` is an optional file extension (e.g. `"flac"`, `"mp3"`)
   * that speeds up probing; pass `null` to auto-detect.
   */
  initialize(codecRegistryHint?: string | undefined | null): boolean
  decode(): DecodeResult | null
  flush(): void
  free(): void
}

export interface DecodeResult {
  samples: Buffer
  sampleRate: number
  channels: number
}
