/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * FLAC (and many other seekable formats) requires random access — symphonia's
 * format reader seeks backward to read STREAMINFO, SEEKTABLE, and frame-sync
 * points. Feeding it a live-growing buffer causes seek-out-of-bounds errors
 * mid-stream that silently stop output. By accumulating the full file and
 * creating a `Cursor<Vec<u8>>` source at probe time, all seeks succeed.
 *
 * Lifecycle
 * 1. `push(chunk)` — accumulate compressed data.
 * 2. `closeInput()` — signal end of input.
 * 3. `initialize(hint?)` — probe the format (requires `closeInput()` first).
 * 4. `decode()` in a loop until it returns `null`.
 * 5. `free()` — release resources.
 */
export declare class SymphoniaDecoder {
  constructor()
  push(chunk: Buffer): void
  closeInput(): void
  /**
   * Returns the number of bytes still in the pre-probe accumulation buffer.
   * This is 0 after `initialize()` because the buffer is moved into the reader.
   */
  get bufferedBytes(): number
  get isProbed(): boolean
  /**
   * Probe the format and set up the decoder.
   * Requires `closeInput()` to have been called first.
   * `codec_registry_hint` is an optional file extension (e.g. `"flac"`, `"mp3"`)
   * that speeds up probing; pass `null` to auto-detect.
   */
  initialize(codecRegistryHint?: string | undefined | null): boolean
  decode(): DecodeResult | null
  flush(): void
  free(): void
}

export interface DecodeResult {
  samples: Buffer
  sampleRate: number
  channels: number
}
